server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-aqgw8ekzpp-stack-awsebrdsdatabase-q8gtlahybk6z.cmr9g0lsp4p5.eu-west-3.rds.amazonaws.com:5432/ebdb
    username: osm
    password: azerty.123..
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet